name: glotalot
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.7.0
  - async-timeout=4.0.2
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - conda=23.3.1
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - cryptography=41.0.1
  - deprecated=1.2.13
  - exceptiongroup=1.1.1
  - fastapi=0.97.0
  - fmt=9.1.0
  - icu=72.1
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.2
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libiconv=1.17
  - libmamba=1.4.2
  - libmambapy=1.4.2
  - libnghttp2=1.52.0
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libuuid=1.41.5
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.5
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.4.2
  - ncurses=6.4
  - openssl=3.1.1
  - packaging=23.1
  - pip=23.1.2
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.9
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.11
  - python_abi=3.10
  - readline=8.2
  - redis=5.0.3
  - redis-py=4.3.4
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.31
  - ruamel.yaml.clib=0.2.7
  - setuptools=67.8.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - starlette=0.27.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.65.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=2.0.3
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.4.2
  - yaml-cpp=0.7.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
